server:
  port: 1000
spring:
  profiles: dev
  application:
    name: springcloud-cpnfig-client
eureka:
  client:
    service-url:
      defaultZone: http://zjjnb1109000.com:9000/eureka/
---
server:
  port: 1001
spring:
  profiles: test
  application:
    name: springcloud-cpnfig-client
eureka:
  client:
    service-url:
      defaultZone: http://zjjnb1109000.com:9000/eureka/